# coding: utf-8

"""
    Gentrace API

    These API routes are designed to ingest events from clients.  # noqa: E501

    The version of the OpenAPI document: 0.22.2
    Generated by: https://openapi-generator.tech
"""

from gentrace.paths.v2_pipelines.get import V2PipelinesGet
from gentrace.paths.v2_test_cases.get import V2TestCasesGet
from gentrace.paths.v2_test_results.get import V2TestResultsGet


class V2Api(
    V2PipelinesGet,
    V2TestCasesGet,
    V2TestResultsGet,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
