name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: python
          path: package

      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs['package--release_created'] }}

      - uses: actions/setup-node@v3
        with:
          node-version: "18.15.0"
          cache: "yarn"
          cache-dependency-path: package/yarn.lock
        if: ${{ steps.release.outputs['package--release_created'] }}

      # TODO: Prepare for PyPI deploy